version: '3.8'
services:
  db:
    build: .
    container_name: unit-test-tutorial
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: anime_list
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
